import { createHash } from 'node:crypto'
import { test, expect } from '@playwright/test'
import { capture, captureCrop, editor, expectImageSource, expectSharedChat, importMaterial, jumpToPage, messages, openStudy, originalImage, savedConversations, selectSourceCrop, send, sentSource } from './shared'

// Amano et al. (2023), PLOS Biology, CC BY. Public PDF fetched/hash-pinned per
// acceptance run; the full article is never committed or bundled.
const PDF = 'https://journals.plos.org/plosbiology/article/file?id=10.1371/journal.pbio.3002184&type=printable'
const SHA256 = '0012515e110c81d8fe0a739568c0c20c1521938595851e2b8acfe22be7ce2b8a'
const ABSTRACT = { x: 320 / 1020, y: 655 / 1320, width: 647 / 1020, height: 402 / 1320 }
const FIGURE = { x: 148 / 1020, y: 106 / 1320, width: 821 / 1020, height: 1102 / 1320 }
const PANEL = { x: 148 / 1020, y: 106 / 1320, width: 414 / 1020, height: 291 / 1320 }
let bytes: Buffer

test.describe.configure({ timeout: 90_000 })
test.beforeAll(async ({ request }) => {
  const response = await request.get(PDF, { timeout: 45_000 })
  expect(response.ok()).toBeTruthy()
  bytes = await response.body()
  expect(createHash('sha256').update(bytes).digest('hex')).toBe(SHA256)
})
test.beforeEach(async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 1250 })
  await openStudy(page)
  await importMaterial(page, { name: 'Amano-et-al-2023.pdf', mimeType: 'application/pdf', buffer: bytes })
  await expect(page.getByRole('spinbutton', { name: '页码' })).toHaveAttribute('max', '27')
  await expect(page.getByRole('button', { name: '帮助方式', exact: true })).toContainText('阅读问答')
  await expect(page.locator('.kv-study-reading-controls textarea')).toHaveCount(0)
  await expect(page.locator('.kv-study-reader-extracted')).toHaveCount(0)
})

test('real English abstract goes through shared Chat attachments, messages, source return and reload', async ({ page }, info) => {
  const fullPage = await originalImage(page, SHA256)
  await capture(page, info, 'shared-chat-reading-fresh-desktop.png')
  const question = '请把摘要前两句译成自然的中文，并解释 impediment 在这里的意思。作者的主要判断是什么？'
  await send(page, question, 'amano-abstract')
  await expect(messages(page)).toContainText('演示阅读（非真实模型调用）')
  const full = await sentSource(page, 0, 1, 'read', fullPage)
  expect(full.studySource?.attempt).toBe('')
  expect(full.studySource?.region).toBeNull()
  expect(full.content).toBe(question)
  expect(full.content).not.toContain('By surveying 908 researchers')
  await selectSourceCrop(page, ABSTRACT)
  const crop = await originalImage(page, SHA256)
  expect(crop === fullPage).toBe(false)
  await send(page, question, 'amano-abstract')
  const selected = await sentSource(page, 1, 1, 'read', crop)
  expect(selected.studySource?.region).not.toBeNull()
  await captureCrop(page, info, 'shared-chat-original-abstract.png')
  await capture(page, info, 'shared-chat-abstract-desktop.png')
  await send(page, '请总结整篇论文的全部方法、结果和局限。', 'amano-whole-paper')
  await sentSource(page, 2, 1, 'read', crop)
  await expect(messages(page)).toContainText('不能据此总结整篇论文')
  const stored = (await savedConversations(page)).find(item => item.id === full.conversationId)!
  expect(stored.messages.filter(message => message.role === 'user')).toHaveLength(3)
  expect(stored.messages.filter(message => message.role === 'assistant')).toHaveLength(3)
  expect(stored.study_context?.materialId).toBe(SHA256)
  await jumpToPage(page, 4)
  await editor(page).fill('第 4 页未发送的阅读问题')
  await jumpToPage(page, 1)
  await messages(page).locator('.chat-scroll-viewport').evaluate(node => { node.scrollTop = 0; node.dispatchEvent(new Event('scroll')) })
  await page.getByRole('button', { name: '来源：第 1 页', exact: true }).click()
  await expectImageSource(page.locator('.kv-study-reader-preview img'), fullPage)
  await page.getByRole('button', { name: '来源：第 1 页 · 选区', exact: true }).first().click()
  await expectImageSource(page.locator('.kv-study-reader-preview img'), crop)
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
  await page.reload()
  await expectSharedChat(page)
  await expectImageSource(page.locator('.kv-study-reader-preview img'), crop)
  expect((await savedConversations(page)).find(item => item.id === full.conversationId)?.messages).toHaveLength(6)
  await jumpToPage(page, 4)
  await expect(editor(page)).toHaveText('第 4 页未发送的阅读问题')
  await info.attach('reading-source-observations.json', { body: JSON.stringify({ source: PDF, sha256: SHA256, authors: 'Amano et al. (2023)', license: 'CC BY', pageCount: 27, page: 1, region: ABSTRACT, sharedChatOwner: true, exactGenericAttachment: true, sharedHistoryRestored: true, teachingValidation: 'Fixed simulated replies; not live-model translation or scope validation. Backend prompt policy is covered by Rust tests.' }, null, 2), contentType: 'application/json' })
})

test('real figure retains complete image and typed source through shared Chat history and mobile Ask', async ({ page }, info) => {
  await jumpToPage(page, 4)
  await selectSourceCrop(page, FIGURE)
  const figure = await originalImage(page, SHA256)
  await captureCrop(page, info, 'shared-chat-original-figure.png')
  await capture(page, info, 'shared-chat-figure-selection-desktop.png')
  const question = '请解释图 1 的 A 面板：横纵轴、颜色、线型和阴影分别表示什么？这能证明因果关系吗？'
  const call = await send(page, question, 'amano-figure')
  await sentSource(page, 0, 4, 'read', figure)
  await expect(messages(page)).toContainText('95% 置信区间')
  await expect(messages(page)).toContainText('不能证明因果')
  await capture(page, info, 'shared-chat-figure-answer-desktop.png')
  await selectSourceCrop(page, PANEL)
  const panel = await originalImage(page, SHA256)
  await send(page, '只看当前选区，这几条彩色线和阴影各代表什么？', 'amano-missing-legend')
  await sentSource(page, 1, 4, 'read', panel)
  await expect(messages(page)).toContainText('缺少图例和完整图注')
  await messages(page).locator('.chat-scroll-viewport').evaluate(node => { node.scrollTop = 0; node.dispatchEvent(new Event('scroll')) })
  await page.getByRole('button', { name: '来源：第 4 页 · 选区', exact: true }).first().click()
  await expectImageSource(page.locator('.kv-study-reader-preview img'), figure)
  await page.locator('.kv-study-notes > summary').click()
  await page.getByLabel('本页笔记', { exact: true }).fill('先核对轴、图例和图注；区分原图信息与自己的推断。')
  await page.locator('.kv-study-notes > summary').click()
  await jumpToPage(page, 1)
  await editor(page).fill('摘要页未发送的问题')
  await jumpToPage(page, 4)
  await expectImageSource(page.locator('.kv-study-reader-preview img'), figure)
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
  await page.reload()
  await expectSharedChat(page)
  await expectImageSource(page.locator('.kv-study-reader-preview img'), figure)
  expect((await savedConversations(page)).find(item => item.id === call.conversationId)?.messages).toHaveLength(4)
  await page.locator('.kv-study-notes > summary').click()
  await expect(page.getByLabel('本页笔记', { exact: true })).toHaveValue('先核对轴、图例和图注；区分原图信息与自己的推断。')
  await page.locator('.kv-study-notes > summary').click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('tab', { name: '阅读', exact: true }).click()
  await page.locator('.kv-study-reader-scroll').evaluate(node => { node.scrollTop = 0 })
  await capture(page, info, 'shared-chat-reading-mobile-source-light.png')
  await page.getByRole('button', { name: '问这个区域', exact: true }).click()
  await expect(editor(page)).toBeFocused()
  const anchor = page.getByRole('button', { name: '查看第 4 页选区', exact: true })
  await expectImageSource(anchor.locator('img'), figure)
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
  await capture(page, info, 'shared-chat-reading-mobile-help-light.png')
  await page.getByRole('button', { name: 'Toggle theme' }).click()
  await capture(page, info, 'shared-chat-reading-mobile-help-dark.png')
  await anchor.click()
  await expect(page.getByRole('tab', { name: '阅读', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expectImageSource(page.locator('.kv-study-reader-preview img'), figure)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await info.attach('figure-source-observations.json', { body: JSON.stringify({ source: PDF, sha256: SHA256, page: 4, fullFigure: FIGURE, missingLegend: PANEL, originalPixelsSavedAsChatAttachment: true, sharedSourceHistoryRestored: true, mobileAskDoesNotSend: true, teachingValidation: 'Fixed visibly simulated replies; not live-model figure comprehension' }, null, 2), contentType: 'application/json' })
})
