import { test, expect } from '@playwright/test'
import { attempt, capture, composer, editor, expectImageSource, expectSharedChat, importMaterial, jumpToPage, material, messages, openStudy, originalImage, savedConversations, scannedPdf, selectMode, send, sendButton, sentSource } from './shared'

test.beforeEach(async ({ page }) => { await openStudy(page) })

test('Study embeds one real Chat composer and preserves normal Chat and per-page draft isolation', async ({ page }, info) => {
  await page.getByRole('button', { name: 'Normal Chat', exact: true }).click()
  const normal = page.locator('[data-composer-presentation="chat"] .chat-composer-editor[role="textbox"]')
  await expect(normal).toBeVisible()
  await normal.fill('Ordinary Chat draft must stay ordinary')
  await page.getByRole('button', { name: 'Study', exact: true }).click()
  const id = await importMaterial(page, material())
  await expectSharedChat(page)
  await expect(editor(page)).toHaveText('')
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
  await editor(page).fill('Reading page one draft')
  await jumpToPage(page, 2)
  await editor(page).fill('Reading page two draft')
  await page.getByRole('button', { name: 'Normal Chat', exact: true }).click()
  await expect(normal).toHaveText('Ordinary Chat draft must stay ordinary')
  await expect(page.locator('[data-chat-composer="true"]')).toHaveCount(1)
  await expect(page.locator('[data-composer-presentation="reading"]')).toHaveCount(0)
  await normal.press('Enter')
  await expect.poll(() => page.evaluate(() => window.__studyTest.requests.length)).toBe(1)
  const ordinary = await page.evaluate(() => window.__studyTest.requests[0])
  expect(ordinary.studySource).toBeUndefined()
  expect(ordinary.attachments).toHaveLength(0)
  await expect.poll(async () => (await savedConversations(page)).find(item => item.id === ordinary.conversationId)?.messages.at(-1)?.stream_outcome).toBe('completed')
  await page.getByRole('button', { name: 'Study', exact: true }).click()
  await expectSharedChat(page)
  await expect(editor(page)).toHaveText('Reading page two draft')
  await jumpToPage(page, 1)
  await expect(editor(page)).toHaveText('Reading page one draft')
  const image = await originalImage(page, id)
  const reading = await send(page, 'Explain the claim on this page')
  await sentSource(page, 1, 1, 'read', image)
  expect(reading.conversationId).not.toBe(ordinary.conversationId)
  const all = await savedConversations(page)
  expect(all.find(item => item.id === ordinary.conversationId)?.messages.some(message => message.content === 'Explain the claim on this page')).toBe(false)
  expect(all.find(item => item.id === reading.conversationId)?.messages.some(message => message.content.includes('Ordinary Chat draft'))).toBe(false)
  await capture(page, info, 'shared-chat-reading-desktop.png')
  await jumpToPage(page, 2)
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
  await page.reload()
  await expectSharedChat(page)
  await expect(editor(page)).toHaveText('Reading page two draft')
  await jumpToPage(page, 1)
  await expect(messages(page)).toContainText('Simulated shared Chat reply')
})

test('the shared composer and model menus retain drafts, keyboard dismissal and vision-only choices', async ({ page }, info) => {
  await importMaterial(page, material())
  await editor(page).fill('Preserve this question while choosing help')
  const mode = page.getByRole('button', { name: '帮助方式', exact: true })
  await expect(mode).toContainText('阅读问答')
  await mode.click()
  await expect(page.getByRole('option')).toHaveText(['阅读问答', '讲清概念', '提示一步', '检查我的解答', '完整解答'])
  await page.keyboard.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(mode).toBeFocused()
  const model = composer(page).locator('button[aria-haspopup="menu"]')
  await expect(model).toContainText('test-vision')
  await model.focus(); await model.press('Enter')
  const menu = page.locator('.chat-model-selector-menu')
  await expect(menu).toBeVisible()
  await expect(menu.getByRole('button', { name: 'test-text', exact: true })).toHaveCount(0)
  await expect(menu.getByRole('button', { name: 'test-vision-alt', exact: true })).toBeVisible()
  await page.keyboard.press('ArrowDown'); await page.keyboard.press('Escape')
  await expect(menu).toHaveCount(0)
  await expect(model).toBeFocused()
  await expect(editor(page)).toHaveText('Preserve this question while choosing help')
  await model.click(); await menu.getByRole('button', { name: 'test-vision-alt', exact: true }).click()
  await expect(model).toContainText('test-vision-alt')
  await page.getByRole('button', { name: '补充说明', exact: true }).click()
  await attempt(page).fill('My own interpretation stays optional')
  const contextWidth = (await attempt(page).boundingBox())!.width
  const composerWidth = (await composer(page).locator('[data-chat-composer="true"]').boundingBox())!.width
  expect(contextWidth, 'Expanded context must use the shared composer width').toBeGreaterThanOrEqual(composerWidth * 0.85)
  await capture(page, info, 'shared-chat-reading-expanded-context-desktop.png')
  await page.getByRole('button', { name: '补充说明', exact: true }).click()
  await selectMode(page, '检查我的解答')
  await expect(attempt(page)).toHaveValue('My own interpretation stays optional')
  await attempt(page).fill('')
  await expect(sendButton(page)).toBeDisabled()
  await editor(page).press('Enter')
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
  await attempt(page).fill('I tried substitution\nu = x³; du = 3x² dx\n∫ x²/(1+x⁶) dx = (1/3)∫du/(1+u²)')
  const attemptWidth = (await attempt(page).boundingBox())!.width
  expect(attemptWidth, 'The formula attempt must not be squeezed into a narrow side column').toBeGreaterThanOrEqual(composerWidth * 0.85)
  await expect(sendButton(page)).toBeEnabled()
  await editor(page).dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
  await capture(page, info, 'shared-chat-reading-menu-and-context.png')
})

test('mobile Ask shares original selection with the common composer without sending', async ({ page }, info) => {
  await importMaterial(page, material())
  await editor(page).fill('Keep this unsent reading question')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('tab', { name: '阅读', exact: true }).click()
  await page.getByRole('button', { name: '键盘框选', exact: true }).click()
  const paper = page.locator('.kv-study-reader-paper')
  await paper.press('ArrowLeft'); await paper.press('Shift+ArrowDown')
  const image = (await page.locator('.kv-study-reader-preview img').getAttribute('src'))!
  await page.getByRole('button', { name: '问这个区域', exact: true }).click()
  await expect(editor(page)).toBeFocused()
  await expect(editor(page)).toHaveText('Keep this unsent reading question')
  await expectSharedChat(page)
  const source = page.getByRole('button', { name: '查看第 1 页选区', exact: true })
  await expectImageSource(source.locator('img'), image)
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
  const model = composer(page).locator('button[aria-haspopup="menu"]')
  await model.click(); await page.keyboard.press('Escape')
  await capture(page, info, 'shared-chat-reading-mobile-help.png')
  await page.getByRole('button', { name: 'Toggle theme' }).click()
  await capture(page, info, 'shared-chat-reading-mobile-help-dark.png')
  await source.click()
  await expect(paper).toBeFocused()
  await expect(page.locator('.kv-study-reader-region')).toBeVisible()
  await page.getByRole('button', { name: '使用整页', exact: true }).click()
  await page.getByRole('button', { name: '问这一页', exact: true }).click()
  await expect(page.getByRole('button', { name: '查看第 1 页', exact: true })).toBeVisible()
  await expect(editor(page)).toHaveText('Keep this unsent reading question')
  await page.setViewportSize({ width: 390, height: 568 })
  await editor(page).fill(Array.from({ length: 40 }, (_, i) => `Reading note ${i + 1}`).join('\n'))
  await sendButton(page).scrollIntoViewIfNeeded()
  await expect(sendButton(page)).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
})

for (const models of ['text-only', 'none']) test(`Study cannot send without an eligible vision model (${models})`, async ({ page }) => {
  await openStudy(page, `?models=${models}`)
  await importMaterial(page, material())
  await editor(page).fill('Explain this original image')
  await expect(sendButton(page)).toBeDisabled()
  await editor(page).press('Enter')
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
  expect(await page.evaluate(() => window.__studyTest.savedImages)).toHaveLength(0)
  await page.locator('.kv-study-notes > summary').click()
  await page.getByLabel('本页笔记', { exact: true }).fill('Reading and notes still work.')
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
})

test('attachment failures preserve the common draft, provider failures retry the exact stored source', async ({ page }) => {
  const id = await importMaterial(page, material())
  const image = await originalImage(page, id)
  await page.evaluate(() => { window.__studyTest.failAttachmentNext = true })
  await editor(page).fill('Keep this question if saving the source fails')
  await sendButton(page).click()
  await expect(messages(page)).toContainText('Simulated attachment storage full')
  await expect(editor(page)).toHaveText('Keep this question if saving the source fails')
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
  await page.evaluate(() => { window.__studyTest.failNext = true })
  await sendButton(page).click()
  await expect(messages(page)).toContainText('Simulated provider unavailable')
  await expect(editor(page)).toHaveText('')
  const failed = await sentSource(page, 0, 1, 'read', image)
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.__studyTest.requests.length)).toBe(2)
  const retried = await sentSource(page, 1, 1, 'read', image)
  expect(retried.kind).toBe('retry')
  expect(retried.attachments).toEqual(failed.attachments)
  expect(retried.studySource).toEqual(failed.studySource)
  await expect.poll(async () => (await savedConversations(page)).find(item => item.id === failed.conversationId)?.messages.at(-1)?.stream_outcome).toBe('completed')
  expect(await page.evaluate(() => window.__studyTest.savedImages.length)).toBe(1)
})

test('shared streaming cancellation preserves a partial reply and late completion cannot replace another page', async ({ page }, info) => {
  await importMaterial(page, material())
  await selectMode(page, '提示一步')
  await page.evaluate(() => { window.__studyTest.hold = true })
  await editor(page).fill('One hint before I continue')
  await editor(page).press('Enter')
  await expect(page.getByRole('button', { name: '停止生成', exact: true })).toBeVisible()
  await expect(messages(page)).toContainText('Simulated shared Chat reply')
  await editor(page).press('Enter')
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(1)
  await page.getByRole('button', { name: '停止生成', exact: true }).click()
  const first = await page.evaluate(() => window.__studyTest.requests[0])
  await expect.poll(async () => (await savedConversations(page)).find(item => item.id === first.conversationId)?.messages.at(-1)?.stream_outcome).toBe('cancelled')
  expect(await page.evaluate(() => window.__studyTest.cancelled)).toEqual([first.conversationId])
  await page.evaluate(() => { window.__studyTest.rawReply = 'Simulated late reply belongs only to page one.'; window.__studyTest.hold = true })
  await editor(page).fill('A held page one reply')
  await sendButton(page).click()
  await expect.poll(() => page.evaluate(() => window.__studyTest.requests.length)).toBe(2)
  await jumpToPage(page, 2)
  await editor(page).fill('Independent page two draft')
  await page.evaluate(() => { window.__studyTest.hold = false })
  await expect.poll(async () => (await savedConversations(page)).find(item => item.id === first.conversationId)?.messages.at(-1)?.stream_outcome).toBe('completed')
  await expect(editor(page)).toHaveText('Independent page two draft')
  await expect(messages(page)).not.toContainText('Simulated late reply')
  await jumpToPage(page, 1)
  await expect(messages(page)).toContainText('Simulated late reply belongs only to page one.')
  await capture(page, info, 'shared-chat-reading-cancel-and-late-navigation.png')
})

test('duplicate, corrupt and same-name materials retain the real reader and page ownership', async ({ page }) => {
  await importMaterial(page, material())
  await importMaterial(page, material())
  await expect(page.locator('.kv-study-document-list button')).toHaveCount(1)
  await importMaterial(page, material('Reading handout.pdf', ['Different bytes under the same filename.']))
  await expect(page.locator('.kv-study-document-list button')).toHaveCount(2)
  await page.getByLabel('导入 PDF 或图片').setInputFiles({ name: 'broken.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-invalid') })
  await expect(page.locator('.kv-study [role="alert"]')).toBeVisible()
  await expect(page.locator('.kv-study-document-list button')).toHaveCount(2)
  const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 200; canvas.height = 120; const ctx = canvas.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 200, 120); ctx.fillStyle = 'black'; ctx.font = '18px sans-serif'; ctx.fillText('An image-only passage', 5, 45); return canvas.toDataURL().split(',')[1] })
  const id = await importMaterial(page, { name: 'image-only.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') })
  const source = await originalImage(page, id)
  await send(page, 'Explain what is visible in this image')
  await sentSource(page, 0, 1, 'read', source)
  await expect(page.locator('.kv-study-reader-extracted')).toHaveCount(0)
})

test('an image-only scanned PDF sends the original image with no text workflow', async ({ page }) => {
  const jpeg = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 720; canvas.height = 900
    const ctx = canvas.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 720, 900)
    ctx.fillStyle = 'black'; ctx.font = '24px sans-serif'; ctx.fillText('A scanned English passage', 45, 90)
    return canvas.toDataURL('image/jpeg').split(',')[1]
  })
  const id = await importMaterial(page, { name: 'scan-without-text.pdf', mimeType: 'application/pdf', buffer: scannedPdf(Buffer.from(jpeg, 'base64')) })
  const source = await originalImage(page, id)
  const call = await send(page, '请解释这张扫描页里的内容')
  await sentSource(page, 0, 1, 'read', source)
  expect(call.content).not.toContain('A scanned English passage')
  await expect(page.locator('.kv-study-reader-extracted')).toHaveCount(0)
  await expect(page.getByLabel('修正后的题目文字')).toHaveCount(0)
})

test('material storage errors keep the shared draft and retry before reload', async ({ page }, info) => {
  await importMaterial(page, material())
  await page.evaluate(() => {
    const put = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (...args: Parameters<IDBObjectStore['put']>) {
      if (this.name === 'documents') throw new DOMException('Simulated full disk', 'QuotaExceededError')
      return put.apply(this, args)
    }
    Reflect.set(window, '__restoreStudyStorage', () => { IDBObjectStore.prototype.put = put })
  })
  await editor(page).fill('Retain the common composer draft while disk is full')
  await expect(page.locator('.kv-study [role="alert"]')).toContainText('材料草稿保存失败')
  await expect(editor(page)).toHaveText('Retain the common composer draft while disk is full')
  await capture(page, info, 'shared-chat-reading-storage-error.png')
  await page.evaluate(() => Reflect.get(window, '__restoreStudyStorage')())
  await page.getByRole('button', { name: '重试保存', exact: true }).click()
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
  await page.reload()
  await expectSharedChat(page)
  await expect(editor(page)).toHaveText('Retain the common composer draft while disk is full')
})

test('a stale second window cannot overwrite the newer material note', async ({ page, context }) => {
  await importMaterial(page, material())
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
  const second = await context.newPage()
  await openStudy(second); await expectSharedChat(second)
  await page.locator('.kv-study-notes > summary').click()
  await page.getByLabel('本页笔记', { exact: true }).fill('Keep the newer material note from window A.')
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
  await editor(second).fill('A stale unsaved question from window B')
  await expect(second.locator('.kv-study [role="alert"]')).toContainText('材料草稿保存失败')
  await second.getByRole('button', { name: '重新读取已保存版本', exact: true }).click()
  await second.getByRole('alertdialog').getByRole('button', { name: '重新读取', exact: true }).click()
  await second.locator('.kv-study-notes > summary').click()
  await expect(second.getByLabel('本页笔记', { exact: true })).toHaveValue('Keep the newer material note from window A.')
  await second.close()
})

test('all legacy outcomes migrate once into Chat while original backup and missing-image limits remain', async ({ page }) => {
  const materialId = await importMaterial(page, material())
  await expect(page.getByText('材料草稿保存在此设备', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Normal Chat', exact: true }).click()
  await expect(composer(page)).toHaveCount(0)
  const originalBackup = await page.evaluate(id => new Promise<string>((resolve, reject) => {
    const open = indexedDB.open('kivio-study')
    open.onerror = () => reject(open.error)
    open.onsuccess = () => {
      const db = open.result
      const tx = db.transaction(['documents', 'meta'], 'readwrite')
      let archive = ''
      tx.onerror = () => { db.close(); reject(tx.error) }
      tx.oncomplete = () => { db.close(); localStorage.setItem('kivio-chat-dev-conversations', '[]'); resolve(archive) }
      const documents = tx.objectStore('documents'), meta = tx.objectStore('meta')
      const get = documents.get(id)
      get.onsuccess = () => {
        const record = get.result, previousBytes = record.metadataBytes
        record.document.pages['1'] = { question: 'Legacy unsent draft', attempt: 'Legacy optional thought', correctedText: 'ARCHIVED_MANUAL_TEXT_NOT_SENT', notes: 'Legacy note retained', region: null,
          history: ['complete', 'error', 'cancelled', 'interrupted', 'streaming'].map((status, index) => ({ id: `legacy-${status}`, mode: 'read', question: `Legacy ${status} question`, attempt: '', sourceText: 'ARCHIVED_EXTRACTED_TEXT_NOT_SENT', sourceImageUsed: true, region: null, answer: `Legacy ${status} answer`, status, ...(status === 'error' ? { error: 'Legacy provider failure' } : {}), createdAt: index + 1, providerId: 'study-fixture', model: 'test-vision', page: 1 })) }
        archive = JSON.stringify(record.document.pages['1'])
        record.metadataBytes = new TextEncoder().encode(JSON.stringify(record.document)).byteLength
        documents.put(record); meta.delete(`chat:${id}:1`)
        const workspace = meta.get('workspace')
        workspace.onsuccess = () => meta.put({ ...workspace.result, totalBytes: workspace.result.totalBytes - previousBytes + record.metadataBytes })
      }
    }
  }), materialId)
  // This is a pre-upgrade startup snapshot. A hash-only goto keeps the already
  // loaded Study and composer stores alive, so reload the normal route first.
  await page.reload()
  await openStudy(page)
  await expectSharedChat(page)
  await expect(editor(page)).toHaveText('Legacy unsent draft')
  const conversationId = `conv_study_${materialId}_1`
  const migrated = (await savedConversations(page)).find(item => item.id === conversationId)!
  expect(migrated.messages).toHaveLength(10)
  expect(migrated.messages.filter(message => message.role === 'assistant').map(message => message.stream_outcome)).toEqual(['completed', 'error', 'cancelled', 'interrupted', 'interrupted'])
  expect(migrated.messages.find(message => message.content === 'Legacy error answer')?.study_legacy_error).toBe('Legacy provider failure')
  expect(JSON.stringify(migrated)).not.toContain('ARCHIVED_')
  await expect(messages(page)).toContainText('旧记录未保存原图')
  await page.reload(); await expectSharedChat(page)
  expect((await savedConversations(page)).find(item => item.id === conversationId)?.messages).toHaveLength(10)
  const backup = await page.evaluate(id => new Promise<string>((resolve, reject) => {
    const open = indexedDB.open('kivio-study'); open.onerror = () => reject(open.error)
    open.onsuccess = () => { const db = open.result; const get = db.transaction('documents').objectStore('documents').get(id); get.onsuccess = () => { db.close(); resolve(JSON.stringify(get.result.document.pages['1'])) } }
  }), materialId)
  expect(backup).toBe(originalBackup)
  expect(await page.evaluate(() => window.__studyTest.requests)).toHaveLength(0)
  // A durable migration receipt must not silently resurrect a removed Chat.
  await page.evaluate(id => { const saved = JSON.parse(localStorage.getItem('kivio-chat-dev-conversations') ?? '[]'); localStorage.setItem('kivio-chat-dev-conversations', JSON.stringify(saved.filter((item: { id: string }) => item.id !== id))) }, conversationId)
  await page.reload()
  await expect(page.locator('.kv-study [role="alert"]')).toContainText('Could not reopen the saved Study conversation')
  expect((await savedConversations(page)).some(item => item.id === conversationId)).toBe(false)
})
