import { test, expect, type Page } from '@playwright/test'

function pdf(pages: string[]) {
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>', `<< /Type /Pages /Kids [${pages.map((_, i) => `${4 + i * 2} 0 R`).join(' ')}] /Count ${pages.length} >>`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']
  pages.forEach((text, i) => {
    const stream = `BT /F1 18 Tf 48 740 Td (${text.replace(/[()\\]/g, '\\$&')}) Tj 0 -40 Td /F1 12 Tf (Show your thinking before asking for help.) Tj ET`
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${5 + i * 2} 0 R >>`, `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`)
  })
  let result = '%PDF-1.4\n'; const offsets = [0]
  objects.forEach((object, i) => { offsets.push(Buffer.byteLength(result)); result += `${i + 1} 0 obj\n${object}\nendobj\n` })
  const xref = Buffer.byteLength(result)
  result += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`
  return Buffer.from(result)
}
const material = (name = 'Calculus handout.pdf', pages = ['1. Why does substitution work?', '2. Differentiate x squared.', '3. Explain the chain rule.']) => ({ name, mimeType: 'application/pdf', buffer: pdf(pages) })
async function importPdf(page: Page, name?: string, pages?: string[]) {
  await page.getByLabel('Import PDF or image').setInputFiles(material(name, pages))
  await expect(page.locator('.kv-study-reader-paper canvas')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
}
async function question(page: Page, value: string) { await page.getByLabel('Question about this page').fill(value) }
async function screenshot(page: Page, path: string) { await page.screenshot({ path, fullPage: true }) }

test.beforeEach(async ({ page }) => { await page.goto('/tests/study-browser/index.html'); await expect(page.getByText('Start with the page that has you stuck')).toBeVisible() })

test('real PDF import, hint, attempt, source history and reload restoration', async ({ page }, info) => {
  await screenshot(page, info.outputPath('study-empty.png'))
  await importPdf(page)
  await page.locator('.kv-study-notes > summary').click()
  await page.getByLabel('Page notes', { exact: true }).fill('I need to track which variable changes.')
  await question(page, 'Why change the variable?')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByText('Simulated test reply: identify', { exact: false }).first()).toBeVisible()
  expect(await page.evaluate(() => window.__studyTest.requests[0].systemPrompt)).toContain('HINT MODE')
  await page.getByRole('radio', { name: 'Check my attempt' }).click()
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
  await page.getByLabel('My attempt', { exact: true }).fill('I differentiated x squared and got x.')
  await question(page, 'Where did I go wrong?')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.locator('.kv-study-turn')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeEnabled()
  expect(await page.evaluate(() => window.__studyTest.requests[1].systemPrompt)).toContain('CHECK MODE')
  await screenshot(page, info.outputPath('study-desktop.png'))
  await page.getByRole('button', { name: /下一页|Next page/ }).click()
  await question(page, 'Second page draft')
  await page.getByRole('button', { name: 'Leave Study' }).click()
  await page.getByRole('button', { name: 'Return to Study' }).click()
  await expect(page.getByLabel('Question about this page')).toHaveValue('Second page draft')
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Question about this page')).toHaveValue('Second page draft')
  await page.locator('.kv-study-history-row').filter({ hasText: 'Where did I go wrong?' }).click()
  await expect(page.locator('.kv-study-page-label')).toHaveText('Page 1')
  await expect(page.getByLabel('My attempt', { exact: true })).toHaveValue('I differentiated x squared and got x.')
  await page.locator('.kv-study-notes > summary').click()
  await expect(page.getByLabel('Page notes', { exact: true })).toHaveValue('I need to track which variable changes.')
  await page.getByRole('button', { name: 'Toggle theme' }).click()
  await screenshot(page, info.outputPath('study-dark.png'))
  await page.goto('/tests/study-browser/index.html?lang=zh')
  await expect(page.getByText('一起想明白', { exact: true })).toBeVisible()
  await screenshot(page, info.outputPath('study-chinese.png'))
})

test('duplicates, same-name different bytes, corrupt import, cancellation and retry', async ({ page }, info) => {
  await importPdf(page)
  await page.getByLabel('Import PDF or image').setInputFiles(material())
  await expect(page.getByText(/already in your library/)).toBeVisible()
  await expect(page.locator('.kv-study-document-list button')).toHaveCount(1)
  await page.getByLabel('Import PDF or image').setInputFiles(material('Calculus handout.pdf', ['Another file with the same name.']))
  await expect(page.locator('.kv-study-document-list button')).toHaveCount(2)
  await page.getByLabel('Import PDF or image').setInputFiles({ name: 'corrupt.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-not-a-document') })
  await expect(page.getByRole('alert').first()).toBeVisible()
  await expect(page.locator('.kv-study-document-list button')).toHaveCount(2)
  await question(page, 'Preserve this question through a failure')
  await page.evaluate(() => { window.__studyTest.failNext = true })
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByText('Simulated provider unavailable. Try again.')).toBeVisible()
  await page.getByRole('button', { name: 'Retry this question' }).click()
  await page.getByRole('button', { name: 'Send retry' }).click()
  await expect(page.locator('.kv-study-turn')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeEnabled()
  await page.evaluate(() => { window.__studyTest.hold = true })
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Stop reply' })).toBeVisible()
  await page.getByRole('button', { name: 'Stop reply' }).click()
  await expect(page.getByText('Stopped. Your draft and partial reply are preserved.')).toBeVisible()
  await expect(page.getByLabel('Question about this page')).toHaveValue('Preserve this question through a failure')
  await screenshot(page, info.outputPath('study-failure-retry.png'))
})

test('region selection, scanned image fallback, explicit solution and keyboard narrow panes', async ({ page }, info) => {
  const image = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 720; canvas.height = 900
    const ctx = canvas.getContext('2d')!; ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 720, 900); ctx.fillStyle = '#111'; ctx.font = '24px sans-serif'; ctx.fillText('Handwritten problem: x + 2 = 5', 45, 90)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  await page.getByLabel('Import PDF or image').setInputFiles({ name: 'scanned-problem.png', mimeType: 'image/png', buffer: Buffer.from(image, 'base64') })
  await expect(page.locator('.kv-study-reader-paper canvas')).toBeVisible()
  await question(page, 'Help me with this equation')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('no readable text')
  await page.getByText('Paste or correct problem text', { exact: true }).click()
  await page.getByLabel('Corrected problem text').fill('Solve x + 2 = 5.')
  await page.getByRole('button', { name: /键盘框选|Select with keyboard/ }).click()
  const paper = page.locator('.kv-study-reader-paper')
  await paper.press('ArrowRight'); await paper.press('Shift+ArrowDown')
  await expect(page.locator('.kv-study-reader-region')).toBeVisible()
  await page.getByRole('button', { name: 'Study model', exact: true }).click()
  await page.getByRole('option', { name: 'test-vision', exact: true }).click()
  await page.getByRole('radio', { name: 'Full solution', exact: true }).click()
  await page.getByRole('button', { name: 'Get full solution', exact: true }).click()
  await expect(page.getByText('Reveal full solution', { exact: true })).toBeVisible()
  await expect(page.getByText('Simulated test reply: identify', { exact: false })).not.toBeVisible()
  await page.getByText('Reveal full solution', { exact: true }).click()
  await expect(page.getByText('Simulated test reply: identify', { exact: false })).toBeVisible()
  expect(await page.evaluate(() => window.__studyTest.requests[0].systemPrompt)).toContain('FULL SOLUTION MODE')
  expect(await page.evaluate(() => window.__studyTest.requests[0].imageDataUrl)).toMatch(/^data:image\/png;base64,/)
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.kv-study-reader-region')).toBeVisible()
  await expect(page.getByLabel('Corrected problem text')).toHaveValue('Solve x + 2 = 5.')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('tab', { name: 'Read', exact: true }).click()
  await page.getByRole('tab', { name: 'Read', exact: true }).press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Help', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('Question about this page')).toBeVisible()
  await screenshot(page, info.outputPath('study-mobile-help.png'))
  await page.getByRole('tab', { name: 'Read', exact: true }).click()
  await screenshot(page, info.outputPath('study-mobile-reader.png'))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})

test('late reply stays on original document while drafts and model selection change', async ({ page }) => {
  await importPdf(page, 'First.pdf')
  await question(page, 'Original first document question')
  await page.evaluate(() => { window.__studyTest.hold = true })
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Stop reply' })).toBeVisible()
  await page.getByLabel('Import PDF or image').setInputFiles(material('Second.pdf', ['A different topic.']))
  await expect(page.getByRole('heading', { name: 'Second.pdf', exact: true })).toBeVisible()
  await question(page, 'Second document unsent draft')
  await page.getByRole('button', { name: 'Study model', exact: true }).click()
  await page.getByRole('option', { name: 'test-vision', exact: true }).click()
  expect(await page.evaluate(() => window.__studyTest.requests[0].model)).toBe('test-text')
  await page.evaluate(() => { window.__studyTest.hold = false })
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeEnabled()
  await expect(page.locator('.kv-study-turn')).toHaveCount(0)
  await page.locator('.kv-study-document-list button').filter({ hasText: 'First.pdf' }).click()
  await expect(page.locator('.kv-study-turn')).toHaveCount(1)
  await expect(page.getByText('Simulated test reply: identify', { exact: false })).toBeVisible()
  await page.locator('.kv-study-document-list button').filter({ hasText: 'Second.pdf' }).click()
  await expect(page.getByLabel('Question about this page')).toHaveValue('Second document unsent draft')
})

test('storage quota failure stays visible, keeps drafts and retries before reload', async ({ page }, info) => {
  await importPdf(page)
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (...args: Parameters<IDBObjectStore['put']>) {
      if (this.name === 'documents') throw new DOMException('Simulated full disk', 'QuotaExceededError')
      return original.apply(this, args)
    }
    Reflect.set(window, '__restoreStudyStorage', () => { IDBObjectStore.prototype.put = original })
  })
  await question(page, 'Keep this even when storage is full')
  await expect(page.getByRole('button', { name: 'Retry save' })).toBeVisible()
  await expect(page.getByText('Not saved', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Question about this page')).toHaveValue('Keep this even when storage is full')
  await screenshot(page, info.outputPath('study-storage-error.png'))
  await page.evaluate(() => { Reflect.get(window, '__restoreStudyStorage')() })
  await page.getByRole('button', { name: 'Retry save' }).click()
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Question about this page')).toHaveValue('Keep this even when storage is full')
})

test('a stale second window cannot overwrite a newer saved note', async ({ page, context }) => {
  await importPdf(page)
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible()
  const second = await context.newPage()
  await second.goto('/tests/study-browser/index.html')
  await expect(second.locator('.kv-study-reader-paper canvas')).toBeVisible()
  await page.locator('.kv-study-notes > summary').click()
  await page.getByLabel('Page notes', { exact: true }).fill('Keep the newer note from window A.')
  await expect(page.getByText('Saved on this device', { exact: true })).toBeVisible()
  await second.getByRole('button', { name: /下一页|Next page/ }).click()
  await expect(second.getByText('Not saved', { exact: true })).toBeVisible()
  await expect(second.getByRole('button', { name: 'Copy unsaved work' })).toBeVisible()
  await second.getByRole('button', { name: 'Reload saved version', exact: true }).click()
  await second.getByRole('alertdialog').getByRole('button', { name: 'Reload saved version', exact: true }).click()
  await expect(second.getByText('Saved on this device', { exact: true })).toBeVisible()
  await second.locator('.kv-study-notes > summary').click()
  await expect(second.getByLabel('Page notes', { exact: true })).toHaveValue('Keep the newer note from window A.')
  await second.close()
})
